%Фильтр Чебышева 1-го рода

function Chebyshev1 = Lab4_Ch1
%UNTITLEDCH1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 17-Oct-2024 19:23:46

% Chebyshev Type I Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

Fpass = 2000;        % Passband Frequency
Fstop = 3000;        % Stopband Frequency
Apass = 0.5;         % Passband Ripple (dB)
Astop = 50;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Chebyshev1 = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]

figure(1)
impz(Chebyshev1)
figure(2)
freqz(Chebyshev1)
figure(3)
grpdelay(Chebyshev1)
figure(4)
zplane(Chebyshev1)

% Реальная Fpass = 2.000122 kHz Fstop = 2.998657 kHz
% Минимальная величина задержки 3.13996, максимальная - 16.08536
% Порядок фильтра 6