%Эллиптический фильтр (фильтр Золотарева—Кауэра)

function Elliptic = Lab4_Elliptic
%LAB4_ELLIPTIC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 17-Oct-2024 19:39:17

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

Fpass = 2000;    % Passband Frequency
Fstop = 3000;    % Stopband Frequency
Apass = 0.5;     % Passband Ripple (dB)
Astop = 50;      % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Elliptic = design(h, 'ellip', 'MatchExactly', match);

% [EOF]

figure(1)
impz(Elliptic)
figure(2)
freqz(Elliptic)
figure(3)
grpdelay(Elliptic)
figure(4)
zplane(Elliptic)

% Реальная Fpass = 2.000122 kHz Fstop = 2.62085 kHz
% Минимальная величина задержки 2.277398, максимальная - 15.1749
% Порядок фильтра 5