%Фильтр Баттерворта

function Butterworth = Lab4_Butterworth
%LAB4 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 17-Oct-2024 18:44:52

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

Fpass = 2000;        % Passband Frequency
Fstop = 3000;        % Stopband Frequency
Apass = 0.5;         % Passband Ripple (dB)
Astop = 50;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Butterworth = design(h, 'butter', 'MatchExactly', match);

% [EOF]

figure(1)
impz(Butterworth)
figure(2)
freqz(Butterworth)
figure(3)
grpdelay(Butterworth)
figure(4)
zplane(Butterworth)

% Реальная Fpass = 2.055054 kHz Fstop = 3.005371 kHz
% Минимальная величина задержки 4.307779, максимальная - 11.18951
% Порядок фильтра 11





