%Синтез с использованием окон

function Window = Lab4_Window
%LAB4_WINDOW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 17-Oct-2024 19:48:32

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

Fpass = 2000;             % Passband Frequency
Fstop = 3000;             % Stopband Frequency
Dpass = 0.028774368332;   % Passband Ripple
Dstop = 0.0031622776602;  % Stopband Attenuation
flag  = 'scale';          % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Window = dfilt.dffir(b);

% [EOF]

figure(1)
impz(Window)
figure(2)
freqz(Window)
figure(3)
zplane(Window)

%Kpmin = -0.01708093 и Kpmax = 0,02616584 в полосе пропускания
%Ksmax = -53.12775 в полосе задерживания
%Порядок фильтра 30