%Синтез путем минимизации среднеквадратической ошибки

function LeastSquares = Lab4_LeastSquares
%LAB4_LEASTSQUARES Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 17-Oct-2024 20:36:49

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N     = 18;    % Order
Fpass = 2000;  % Passband Frequency
Fstop = 3000;  % Stopband Frequency
Wpass = 1;     % Passband Weight
Wstop = 18;    % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
LeastSquares = dfilt.dffir(b);

% [EOF]

figure(1)
freqz(LeastSquares)
%Kpmin = -0.4844071 и Kpmax = 0.1576879 в полосе пропускания
%Ksmax = -34.37349 в полосе задерживания