%Исследование влияния округления коэффициентов фильтра на его параметры.
%Каскад секций 1 порядка

function Hd = Lab5_2
%LAB5_2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 19-Oct-2024 20:05:13

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

N  = 4;     % Order
Fc = 0.25;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc);
Hd = design(h, 'butter');

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);
% Set the arithmetic property.
set(Hd, 'Arithmetic', 'fixed', ...
    'CoeffWordLength', 8, ...
    'CoeffAutoScale', true, ...
    'ProductMode', 'Fullprecision', ...
    'AccumMode', 'KeepMSB', ...
    'AccumWordLength', 40, ...
    'StateWordLength', 16, ...
    'StateFracLength', 15, ...
    'InputWordLength', 16, ...
    'inputFracLength', 15, ...
    'OutputWordLength', 16, ...
    'OutputMode', 'AvoidOverflow', ...
    'signed',        true, ...
    'RoundMode',     'convergent', ...
    'OverflowMode',  'Wrap', ...
    'CastBeforeSum', true);

denormalize(Hd);

% [EOF]

impz(Hd)
zplane(Hd)